### ISSUE TITLE
(Final) Using a Howls.pos function causes strange interactions with resetting music.

### ISSUE THREAD

**Issue by VRushLP** [VRushLP/RigorMortisGame#79] opened 2016-02-27 05:08 UTC

**Comment by tjsg1992** [comment] 2016-02-29 22:17
It looks like this is caused by Howls creating new threads of themselves whenever they are restarted and/or have pos() called. These threads are apparently not protected, so their end timers conflict with each other, causing premature restarts. This has been tentatively fixed by removed all pos() calls from Howls.

**Comment by VRushLP** [comment] 2016-03-07 23:07
I believe this is fixed in the 'jukebox' branch. I'll let someone else close it if they agree.

**Closed as completed** 2016-03-11 19:00 UTC
